### ISSUE TITLE
Preview of version 2.0

### ISSUE THREAD

**Issue by Notavone** [Notavone/discord-panel#47]
Hi everyone!

I know some of you feel like I abandoned this project, but I did not!

I started working on version 2.0 yesterday, let me explain why I took so long :
1. I'm studying computer science and have less time to work on personal projects
2. That's all

In all seriousness, I took my time to think about how I was going to do this because v2 will be a complete rework of the panel which means :
1. I'm scrapping the translations for the moment because a lot of the text may change/be removed/be not implemented yet when I'll release the v2
2. You won't find the same features on the day of the release because I'm doing it from scratch on the client-side, expect it to be really basic

### To-do list before release

Core features: 

- [x] Receive messages from different servers and channels
- [x] Send messages
- [ ] Private messages (not sure)
- [ ] Create invites
- [ ] Manage messages
- [ ] Change token (not sure)

Styling will be done last*

I'll update this list and this issue periodically.

Have a nice day and see you soon!
